[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://blogspace-fxgv.onrender.com/api"
  VITE_APP_NAME = "BlogSpace"
  VITE_APP_URL = "https://blogspacebyharshuu.netlify.app"

[[redirects]]
  from = "/api/*"
  to = "https://blogspace-fxgv.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
